import java.util.Scanner;
public class ExceptionHandleTryCatch_2 {

	public static void main(String[] args) 
	{
		// TODO Auto-generated method stub
		int [] arr = new int[100];
		Scanner sc = new Scanner(System.in);
		
		for(int i = 0 ; i < 3 ; i++)
		{
			try
			{
				System.out.println("피제수입력");
				int result1 = sc.nextInt();
				System.out.println("제수입력");
				int result2 = sc.nextInt();
				
				System.out.println("인덱스입력");
				int result3 = sc.nextInt();
				
				arr[result3] = result1/result2;
				System.out.printf("값출력 : %d 인덱스 값 : %d\n",arr[result3],result3);
			}
			catch(ArithmeticException e)
			{
				i--;
				System.out.println("제수는 0이 될 수 없습니다.");				
				System.out.println(e.getMessage());
			}
			catch(ArrayIndexOutOfBoundsException e)
			{
				i--;
				System.out.println("인덱스범위초과");							
				System.out.println(e.getMessage());
			}
		}
	}

}
